[package]
name = "examples"
version = "0.0.0"
edition = "2021"

[workspace]
members = ["layout", "renderer", "state", "freya", "elements", "components", "hooks", "common", "core", "testing"]

[features]
devtools = ["freya/devtools"]

[dev-dependencies]
freya = { path = "./freya"}
dioxus-native-core-macro = { git = "https://github.com/DioxusLabs/dioxus", rev="4f0f2484fd16aa24b7ff51b9c55aea5c8a9b5c50" }
dioxus = { git = "https://github.com/DioxusLabs/dioxus", rev="4f0f2484fd16aa24b7ff51b9c55aea5c8a9b5c50", features = ["macro", "hooks"]}
dioxus-rsx = { git = "https://github.com/DioxusLabs/dioxus", rev="4f0f2484fd16aa24b7ff51b9c55aea5c8a9b5c50"}
dioxus-native-core = { git = "https://github.com/DioxusLabs/dioxus", rev="4f0f2484fd16aa24b7ff51b9c55aea5c8a9b5c50"}
dioxus-core-macro = { git = "https://github.com/DioxusLabs/dioxus", rev="4f0f2484fd16aa24b7ff51b9c55aea5c8a9b5c50"}
dioxus-hooks = { git = "https://github.com/DioxusLabs/dioxus", rev="4f0f2484fd16aa24b7ff51b9c55aea5c8a9b5c50"}
dioxus-core = { git = "https://github.com/DioxusLabs/dioxus", rev="4f0f2484fd16aa24b7ff51b9c55aea5c8a9b5c50"}
tokio = "1.23.0"
reqwest = {version = "0.11.13", features = ["json"] }
serde = "1.0.152"
tracing-subscriber = "0.2.25"
dioxus-router = { git = "https://github.com/DioxusLabs/dioxus", rev="4f0f2484fd16aa24b7ff51b9c55aea5c8a9b5c50"}

[profile.release]
lto = true
opt-level = 3
